
name: microservices-user-dev
services:
  # ==========================================
  # POSTGRESQL PARA USER SERVICE
  # ==========================================
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-test-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
  #  ports:
  #    - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ==========================================
  # POSTGRESQL PARA PRODUCT SERVICE
  # ==========================================
  postgres-product:
    image: postgres:15-alpine
    container_name: postgres-product
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    # ports:
    #   - "5433:5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  # ==========================================
  # USER SERVICE
  # ==========================================
  user-service:
    build: ./user-service
    image: user-service:1.0
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-dev}
      - SPRING_DATASOURCE_URL=${DB_URL:-jdbc:postgresql://postgres-user:5432/userdb}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-postgres}

    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped

  # ==========================================
  # PRODUCT SERVICE
  # ==========================================
  product-service:
    build: ./product-service
    image: product-service:1.0
    container_name: product-service
    # ports:
    #   - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-product:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      config-server:
        condition: service_healthy
      postgres-product:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# ==========================================
# NETWORKS
# ==========================================
networks:
  microservices-network:
    driver: bridge

# ==========================================
# VOLUMES
# ==========================================
volumes:
  postgres-user-data:
  postgres-product-data: