
name: microservices-user-dev
services:
  # ==========================================
  # POSTGRESQL PARA USER SERVICE
  # ==========================================
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-test-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
  #  ports:
  #    - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
      
  # ==========================================
  # USER SERVICE
  # ==========================================
  user-service:
    build: ./user-service
    image: user-service:1.0
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-user:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped

# ==========================================
# NETWORKS
# ==========================================
networks:
  microservices-network:
    driver: bridge

# ==========================================
# VOLUMES
# ==========================================
volumes:
  postgres-user-data: